### ISSUE TITLE
Ensure predictions page links match

### ISSUE THREAD

**Issue by nickmcm92** [DoubtAvatar-DP2/PHP-SRePS#23]
Will open issue for when predictions page is in master to ensure linsk match

_Originally posted by @nickmcm92 in https://github.com/DoubtAvatar-DP2/PHP-SRePS/pull/22#r506120297_

**Comment by hd-chuong** [comment]
prediction page is included in nav.php

**Comment by nickmcm92** [comment]
Confirmed all updated and working.
