### ISSUE TITLE
Ensure sales report is links are updated or removed

### ISSUE THREAD

**Issue by nickmcm92** [DoubtAvatar-DP2/PHP-SRePS#24]
Will open issue to ensure sales report is links are updated or removed

_Originally posted by @nickmcm92 in https://github.com/DoubtAvatar-DP2/PHP-SRePS/pull/22#r506120955_

**Comment by hd-chuong** [comment]
sales report links are updated in includes/nav.php.

**Comment by nickmcm92** [comment]
Confirmed all updated and working.
